# Generated by Django 4.2.3 on 2023-07-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_accountbook_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type1',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='type2',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='type3',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
