# Generated by Django 4.2.3 on 2023-07-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_type1_money_alter_type2_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbook',
            name='type_name',
            field=models.TextField(default='Type1', verbose_name='type명'),
        ),
    ]
