# Generated by Django 4.2.3 on 2023-07-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(default="", max_length=64, unique=True)),
                ("name", models.CharField(default="", max_length=64, unique=True)),
                ("phone", models.CharField(max_length=11, unique=True)),
                ("birth", models.DateField(auto_now_add=True, verbose_name="출생일")),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
