# Generated by Django 4.2.3 on 2023-07-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_birth_remove_user_phone_user_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
    ]
