# Generated by Django 4.2.3 on 2023-07-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_email_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
    ]
